config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/index'

  get 'pages/show'

  get 'about/index'

  get 'blogs/index'

  get 'contact/index'

  root to: 'static_pages#home'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource)
     about_index_path # ログイン後に遷移したいパス
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def index
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
  <main class="container main" role="main">
    <div class="row">
      <div class="col-xs-12 col-md-12">
        <div class="row feature">
        <section class="row">
          <ul class="thumb-block col-xs-12">
            <li class="clearfix">
              <div class="pull-left col-xs-12 col-sm-5"><%= image_tag 'image1.jpg' %></div>
              <div class="pull-left col-xs-12 col-sm-7">
                <h3>キャッチコピーが入ります</h3>
                <p>ハイクオリティで洗練されたデザイン、ユーザーの心をつかむ機能、そして安心のカスタマーサポート。
                  <br>一度お試しいただければ、その良さをきっとご理解いただけます。</p>
                <a href="sample.html">
                  <button type="button" class="btn btn-primary" aria-label="Right Align">詳しく見る<span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span></button>
                </a>
              </div>
            </li>
          </ul>
        </section>
        <section>
          <h2 class="subtitle">作品一覧</h2>
          <div>
            <ul class="row thumb-box">
              <li class="col-xs-12 col-sm-4">
                <a href="sample.html">
                  <section>
                    <div><%= image_tag 'image1.jpg' %></div>
                    <h3>無料相談会を実施いたします</h3>
                    <p>コンテンツがここに入ります。コンテンツがここに入ります。コンテンツがここに入ります。コンテンツ…</p>
                  </section>
                </a>
              </li>
              <li class="col-xs-12 col-sm-4">
                <a href="sample.html">
                  <section>
                    <div><%= image_tag 'image1.jpg' %></div>
                    <h3>無料相談会を実施いたします</h3>
                    <p>コンテンツがここに入ります。コンテンツがここに入ります。コンテンツがここに入ります。コンテンツ…</p>
                  </section>
               </a>
              </li>
              <li class="col-xs-12 col-sm-4">
                <a href="sample.html">
                  <section>
                    <div><%= image_tag 'image1.jpg' %></div>
                    <h3>無料相談会を実施いたします</h3>
                    <p>コンテンツがここに入ります。コンテンツがここに入ります。コンテンツがここに入ります。コンテンツ…</p>
                  </section>
                </a>
              </li>
            </ul>
          </div>
        </section>


          <h2 class="subtitle">作品一覧</h2>

          <section class="col-xs-12 col-sm-4 feature-block">
            <a href="sample.html">
              <div class="row">
                <p class="col-xs-5 col-sm-12 featureblock-thumbnail"><img src="images/image1.jpg" alt="サンプル画像1" class="img-responsive"></p>
                <h3 class="col-xs-7 col-sm-12 featureblock-title">COMPANY<span>会社概要</span></h3>
              </div>
            </a>
          </section>
          <section class="col-xs-12 col-sm-4 col-sm-4 feature-block">
            <a href="sample.html">
              <div class="row">
                <p class="col-xs-5 col-sm-12  featureblock-thumbnail"><img src="images/image1.jpg" alt="サンプル画像2" class="img-responsive"></p>
                <h3 class="col-xs-7 col-sm-12 featureblock-title">BUSINESS<span>事業紹介</span></h3>
              </div>
            </a>
          </section>
          <section class="col-xs-12 col-sm-4 feature-block">
            <a href="sample.html">
              <div class="row">
                <p class="col-xs-5 col-sm-12  featureblock-thumbnail"><img src="images/image1.jpg" alt="サンプル画像3" class="img-responsive"></p>
                <h3 class="col-xs-7 col-sm-12 featureblock-title">RECRUIT<span>採用情報</span></h3>
              </div>
            </a>
          </section>
        </div>

      </div>
    </div>
  </main>

app/views/blogs/index.html.erb
  <main class="container main" role="main">
    <div class="row">
      <div class="col-xs-12 col-md-12">
        <div class="row feature">



          <h2 class="subtitle">ニュース一覧</h2>

          <section class="col-xs-12 col-sm-4 feature-block">
            <a href="sample.html">
              <div class="row">
                <p class="col-xs-5 col-sm-12 featureblock-thumbnail"><%= image_tag 'image1.jpg' %></p>
                <h3 class="col-xs-7 col-sm-12 featureblock-title">COMPANY<span>会社概要</span></h3>
              </div>
            </a>
          </section>
          <section class="col-xs-12 col-sm-4 col-sm-4 feature-block">
            <a href="sample.html">
              <div class="row">
                <p class="col-xs-5 col-sm-12  featureblock-thumbnail"><%= image_tag 'image1.jpg' %></p>
                <h3 class="col-xs-7 col-sm-12 featureblock-title">BUSINESS<span>事業紹介</span></h3>
              </div>
            </a>
          </section>
          <section class="col-xs-12 col-sm-4 feature-block">
            <a href="sample.html">
              <div class="row">
                <p class="col-xs-5 col-sm-12  featureblock-thumbnail"><%= image_tag 'image1.jpg' %></p>
                <h3 class="col-xs-7 col-sm-12 featureblock-title">RECRUIT<span>採用情報</span></h3>
              </div>
            </a>
          </section>
        </div>

      </div>
    </div>
  </main>

app/views/contact/index.html.erb
  <main class="container main" role="main">
    <div class="row">
      <div class="col-xs-12 col-md-12">
        <div class="row feature">
          <div class="container">
            <div class="page-header">
              <h1>お問い合わせ</h1>
            </div>
              <div class="row">
              <div class="icon col-sm-3 hidden-xs">
                <span class="glyphicon glyphicon-earphone" aria-hidden="true"></span>
                <div class="icon-caption">お電話</div>
              </div>
              <div class="content col-sm-9">
                <h2>お電話によるお問い合わせ</h2>
                <p>
                  該当する内容の電話番号におかけください。
                </p>
                <div class="table-responsive">
                  <table class="table table-striped table-bordered">
                    <thead>
                      <tr>
                        <th>内容</th>
                        <th>電話番号</th>
                        <th>担当</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>サービスに関するお問い合わせ</td>
                        <td>03-0000-0000</td>
                        <td>煌木</td>
                      </tr>
                      <tr>
                        <td>採用に関するお問い合わせ</td>
                        <td>03-0000-0001</td>
                        <td>煌田</td>
                      </tr>
                      <tr>
                        <td>取材に関するお問い合わせ</td>
                        <td>03-0000-0002</td>
                        <td>煌山</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="panel panel-info">
                  <div class="panel-heading">
                    <h3 class="panel-title" id="panel-title">
                      <span class="glyphicon glyphicon-info-sign" aria-hidden="true"></span> 
                      営業時間
                    </h3>
                  </div>
                  <div class="panel-body">
                    平日10時〜19時（土日・祝日は対応しておりません）
                  </div>
                </div>
              </div>
            </div>
            <div class="row">
              <div class="icon col-sm-3 hidden-xs">
                <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span>
                <div class="icon-caption">メール</div>
              </div>
              <div class="content col-sm-9">
                <h2>メールによるお問い合わせ</h2>
                <p>
                  プライバシーポリシーをご確認、ご同意の上、送信ボタンを押してください。<br>
                  お問い合わせの回答は、受付日から3営業日以内をめどにご返信差し上げます。
                </p>
                <form class="form-horizontal">
                  <div class="form-group">
                    <label for="inputCompany" class="col-md-2 control-label">会社名</label>
                    <div class="col-md-10">
                      <input type="text" class="form-control" id="inputCompany" placeholder="例）サンプル株式会社">
                    </div>
                  </div>
                    <div class="form-group">
                    <label for="inputName" class="col-md-2 control-label">氏名</label>
                    <div class="col-md-10">
                      <input type="text" class="form-control" id="inputName" placeholder="例）煌木 太郎">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputEmail" class="col-md-2 control-label">メールアドレス</label>
                    <div class="col-md-10">
                      <input type="email" class="form-control" id="inputEmail" placeholder="例）taro.kirameki@example.com">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputTel" class="col-md-2 control-label">電話番号</label>
                    <div class="col-md-10">
                      <input type="tel" class="form-control" id="inputTel" placeholder="例）0312345678">
                    </div>
                  </div>
                  <div class="form-group">
                    <label for="inputContent" class="col-md-2 control-label">お問い合わせ内容</label>
                    <div class="col-md-10">
                      <textarea class="form-control" id="inputContent" rows="4" placeholder="具体的にお書きください"></textarea>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                      <div class="checkbox">
                        <label>
                          <input type="checkbox">プライバシーポリシーに同意
                        </label>
                      </div>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                      <button type="submit" class="btn btn-default btn-success btn-block">お問い合わせを送信</button>
                    </div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>

      </div>
    </div>
  </main>

app/views/layouts/_footer.html.erb
  <div class="btn-pagetop">
    <div class="container">
      <a href="#pageTop" class="center-block text-center"><i class="glyphicon glyphicon-chevron-up center-block"></i></a>
    </div>
  </div>
  <footer class="footer" role="contentinfo">
    <div class="container">
      <div class="row footer-nav">
        <aside class="col-xs-12 col-sm-6 col-md-3 col-md-push-3">
          <h3 class="footernav-title"><strong class="glyphicon glyphicon-chevron-down">SERVICE</strong></h3>
          <div class="list-group">
            <a href="sample.html">&#8811; サービスその1</a>
            <a href="sample.html">&#8811; サービスその2</a>
            <a href="sample.html">&#8811; サービスその3</a>
          </div>
        </aside>
        <aside class="col-xs-12 col-sm-6 col-md-3 col-md-push-3">
          <h3 class="footernav-title"><strong class="glyphicon glyphicon-chevron-down">PRODUCT</strong></h3>
          <div class="list-group">
            <a href="sample.html">&#8811; 製品その1</a>
            <a href="sample.html">&#8811; 製品その2</a>
            <a href="sample.html">&#8811; 製品その3</a>
          </div>
        </aside>
        <aside class="col-xs-12 col-sm-6 col-md-3 col-md-push-3">
          <h3 class="footernav-title"><strong class="glyphicon glyphicon-chevron-down">COMPANY</strong></h3>
          <div class="list-group">
            <a href="sample.html">&#8811; 会社概要</a>
            <a href="sample.html">&#8811; 事業紹介</a>
            <a href="sample.html">&#8811; 採用情報</a>
          </div>
        </aside>
        <div class="col-xs-12 col-sm-6 col-md-3 col-md-pull-9 footer-icon">
          <p class="footer-logo">
            <a href="index.html"><img src="images/logo.jpg" alt=""></a>
          </p>
        </div>
      </div>
      <div class="copyright">
        <small>Copyright &copy; Kid'Hack</small>
      </div>
    </div>
  </footer>

app/views/layouts/_header.html.erb
  <div id="fb-root"></div>
  <header class="header">
    <div class="container">
      <div class="row">
        <h1 class="site-logo col-xs-9 col-sm-6 col-md-8">
          <a href=""><%= image_tag 'logo.jpg' %></a>
        </h1>
        <div class="col-sm-6 col-md-4">
          <ul class="btnArea">
            <li><a href=""><%= image_tag 'button4.jpg' %></a></li>

          </ul>

        </div>
        <div class="col-xs-3 nav-toggle">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-label="メニュー">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
      </div>
    </div>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="gnav1"><a href="">ホーム</a></li>
            <li><%= link_to "はじめに", about_index_path %></li>
            <li><%= link_to "学習の流れ", about_index_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">お知らせ<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "ブログ", blogs_index_path %></li>
                <li><%= link_to "ブログ", blogs_index_path %></li>
                <li><%= link_to "ブログ", blogs_index_path %></li>
              </ul>
            </li>
            <li><%= link_to "お申し込み", pages_index_path %></li>
            <li><a href="question.html">FAQ</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>
  <div id="carousel-mainvisual" class="key-visual carousel slide jumbotron" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carousel-mainvisual" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-mainvisual" data-slide-to="1"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
      <div class="item active">
        <a href="sample.html" class="center-block"><%= image_tag 'top.jpg' %></a>
      </div>
      <div class="item">
        <a href="sample.html" class="center-block"><%= image_tag 'top.jpg' %></a>
      </div>
    </div>

  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <meta name="keywords" content="小学生,プログラミング,IT教室,ゲーム作り,">
    <meta name="description" content="Kid'Hack">
    <meta name="author" content="">
    <title>小学生向けプログラミン教室 Kid'Hack</title>
    <meta property="og:title" content="小学生向けプログラミン教室 Kid'Hack">
    <meta property="og:description" content="Kid'Hack">
    <meta property="og:type" content="">
    <meta property="og:url" content="">
    <meta property="og:image" content="">
    <meta property="fb:app_id" content="">
    <link rel="canonical" href="">
    <link rel="shortcut icon" type="image/x-icon" href="">
    <link rel="apple-touch-icon" href="">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto+Condensed">
    <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body id="pageTop">
    <%= render 'layouts/header' %>
    
    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/second.html.erb
  <div id="fb-root"></div>
  <header class="header">
    <div class="container">
      <div class="row">
        <h1 class="site-logo col-xs-9 col-sm-6 col-md-8">
          <a href=""><%= image_tag 'logo.jpg' %></a>
        </h1>
        <div class="col-sm-6 col-md-4">
          <ul class="btnArea">
            <li><a href=""><%= image_tag 'button4.jpg' %></a></li>

          </ul>

        </div>
        <div class="col-xs-3 nav-toggle">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false" aria-label="メニュー">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
      </div>
    </div>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="gnav1"><a href="">ホーム</a></li>
            <li><%= link_to "はじめに", about_index_path %></li>
            <li><%= link_to "学習の流れ", about_index_path %></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button">お知らせ<span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "ブログ", blogs_index_path %></li>
                <li><%= link_to "ブログ", blogs_index_path %></li>
                <li><%= link_to "ブログ", blogs_index_path %></li>
              </ul>
            </li>
            <li><%= link_to "お申し込み", contact_index_path %></li>
            <li><a href="question.html">FAQ</a></li>
          </ul>
        </div>
      </div>
    </nav>
  </header>


  </div>

app/views/pages/index.html.erb
<h1>Home#index</h1>
<% if user_signed_in? %>
  Logged in as <strong><%= current_user.email %></strong>.
  <%= link_to "Settings", edit_user_registration_path, :class => "navbar-link" %> |
  <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => "navbar-link" %>
<% else %>
  <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link' %> |
  <%= link_to "Login", new_user_session_path, :class => 'navbar-link' %>
<% end %>
<p>Find me in app/views/home/index.html.erb</p>

app/views/pages/show.html.erb
<h1>Pages#show</h1>
<p>Find me in app/views/pages/show.html.erb</p>

app/views/static_pages/home.html.erb
  <main class="container main" role="main">
    <div class="row">
      <div class="col-xs-12 col-md-12">
        <div class="row feature">
        <section class="row">
          <div class="col-xs-12">
            <h2 class="home-subtitle">Information<span>お知らせ</span></h2>

            <div class="tab-content">
              <ul class="tab-pane row active" id="newsrelease">
                <li class="col-xs-12">
                  <div>
                    <span class="date">2016.03.01</span>
                    <span class="label label-default label-new">New</span>
                  </div>
                  <p class="article-title"><a href="sample.html">ホームページをリニューアルしました。</a></p>
                </li>
                <li class="col-xs-12">
                  <div>
                    <span class="date">2016.02.25</span>
                    <span class="label label-default label-product">プロダクト</span>
                  </div>
                  <p class="article-title"><a href="sample.html">新サービスの発表会を３月に新宿にて行ないます。会員のみなさまには、招待状をお送りしましたので奮ってご参加ください。</a></p>
                </li>

              </ul>

            </div>
          </div>
        </section>
        <section>
          <h2 class="subtitle">スクールの特徴</h2>
          <div>
            <ul class="row thumb-box">
              <li class="col-xs-12 col-sm-4">
                <a href="sample.html">
                  <section>
                    <div><%= image_tag 'image1.jpg' %></div>
                    <h3>無料相談会を実施いたします</h3>
                    <p>コンテンツがここに入ります。コンテンツがここに入ります。コンテンツがここに入ります。コンテンツ…</p>
                  </section>
                </a>
              </li>
              <li class="col-xs-12 col-sm-4">
                <a href="sample.html">
                  <section>
                    <div><%= image_tag 'image1.jpg' %></div>
                    <h3>無料相談会を実施いたします</h3>
                    <p>コンテンツがここに入ります。コンテンツがここに入ります。コンテンツがここに入ります。コンテンツ…</p>
                  </section>
               </a>
              </li>
              <li class="col-xs-12 col-sm-4">
                <a href="sample.html">
                  <section>
                    <div><%= image_tag 'image1.jpg' %></div>
                    <h3>無料相談会を実施いたします</h3>
                    <p>コンテンツがここに入ります。コンテンツがここに入ります。コンテンツがここに入ります。コンテンツ…</p>
                  </section>
                </a>
              </li>
            </ul>
          </div>
        </section>


          <h2 class="subtitle">作品一覧</h2>

          <section class="col-xs-12 col-sm-4 feature-block">
            <a href="sample.html">
              <div class="row">
                <p class="col-xs-5 col-sm-12 featureblock-thumbnail"><%= image_tag 'image1.jpg' %></p>
                <h3 class="col-xs-7 col-sm-12 featureblock-title">COMPANY<span>会社概要</span></h3>
              </div>
            </a>
          </section>
          <section class="col-xs-12 col-sm-4 col-sm-4 feature-block">
            <a href="sample.html">
              <div class="row">
                <p class="col-xs-5 col-sm-12  featureblock-thumbnail"><%= image_tag 'image1.jpg' %></p>
                <h3 class="col-xs-7 col-sm-12 featureblock-title">BUSINESS<span>事業紹介</span></h3>
              </div>
            </a>
          </section>
          <section class="col-xs-12 col-sm-4 feature-block">
            <a href="sample.html">
              <div class="row">
                <p class="col-xs-5 col-sm-12  featureblock-thumbnail"><%= image_tag 'image1.jpg' %></p>
                <h3 class="col-xs-7 col-sm-12 featureblock-title">RECRUIT<span>採用情報</span></h3>
              </div>
            </a>
          </section>
        </div>

      </div>
    </div>
  </main>